"use client";
import { Navbar, Session, Sidebar } from "@/components/dashboard-components";
import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import UploadModal from "@/components/UploadModal";
import { useVerbalContext } from "@/app/context/Index";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { isOpen, setIsOpen } = useVerbalContext();
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        <div className="min-h-screen w-full flex items-center justify-center">
          <div className="w-[50%] bg-map2 object-bottom bg-contain bg-left-bottom bg-no-repeat h-screen flex flex-col items-center justify-center mb-[40px] ">
            <div className="w-[50%] bg-map2 object-bottom bg-contain bg-left-bottom bg-no-repeat h-screen flex flex-col items-center justify-center mb-[40px] ">
              <Image
                src={require("../../assests/logo.png")}
                alt="logo"
                className="w-[263.048px] h-[240px] object-cover"
              />
              <p className="w-[365px] text-center text-[#CCCCCCAA] font-semibold">
                Your Gateway to Web 3 and AI-powered Language Learning!
              </p>
            </div>
          </div>
          <div className="border  bg-[#fff] h-[880px] items-center flex" />
          <div className="w-[50%] bg-map2  bg-right-top bg-no-repeat bg-contain flex items-center justify-center">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
