"use client";
import { Navbar, Session, Sidebar } from "@/components/dashboard-components";
import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import UploadModal from "@/components/UploadModal";
import { useVerbalContext } from "@/app/context/Index";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { isOpen, setIsOpen } = useVerbalContext();
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className="flex items-start gap-5">
          <Sidebar />
          <div className="w-[70%] h-screen overflow-y-scroll scrollbar-hide">
            {isOpen && <UploadModal />}
            {children}
          </div>
          <Session />
        </div>
      </body>
    </html>
  );
}
